FROM golang
WORKDIR /workspace
COPY . .
RUN go install
RUN apt-get update
RUN apt-get install tini
#RUN chmod +x run.sh
#ENTRYPOINT ["tini", "-g", "--", "./run.sh"]
ENTRYPOINT ["tini", "-g", "--", "sh", "-c", "hello \"${0} ${*}\" && sleep infinity"]
CMD ["world"]
