# Add a system package during the build

FROM golang AS build
WORKDIR /app
COPY .. .
RUN apt-get update
RUN apt-get install -y cloc && cloc hello-box.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -a -installsuffix cgo -o hello

FROM scratch
LABEL org.opencontainers.image.authors="me@example.com"
COPY --from=build /app/hello /
ENTRYPOINT ["/hello"]
CMD ["world"]

